# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

jobs:
  unit_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build + Unit + Lint
        run: |
          ./gradlew --stacktrace --no-daemon clean
          ./gradlew assemble
          ./gradlew test
          ./gradlew lint

  connected_android_tests:
    needs: unit_and_lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Emülatörü kur ve enstrümantasyon testlerini çalıştır
      - name: Run connected tests (API 30)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86_64
          profile: pixel_6
          target: default
          emulator-options: -no-window -no-snapshot -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest


